// Generated by CoffeeScript 1.3.3

(function($) {
  var methods, sel;
  sel = require('sel');
  $._select = sel.sel;
  methods = {
    find: function(s) {
      return $(s, this);
    },
    union: function(s, r) {
      return $(sel.union(this, sel.sel(s, r)));
    },
    difference: function(s, r) {
      return $(sel.difference(this, sel.sel(s, r)));
    },
    intersection: function(s, r) {
      return $(sel.intersection(this, sel.sel(s, r)));
    },
    matching: function(s) {
      return $(sel.matching(this, s));
    },
    is: function(s, r) {
      return sel.matching(this, s, r).length > 0;
    }
  };
  methods.and = methods.union;
  methods.not = methods.difference;
  methods.matches = methods.matching;
  $.pseudos = sel.pseudos;
  return $.ender(methods, true);
})(ender);
